import { createElement } from "lwc";
import L4lCreateClientBOC from "c/l4lCreateClientBOC";

describe("c-l4-l-create-client-boc", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-l4-l-create-client-boc", {
      is: L4lCreateClientBOC
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
