System.debug(L4LSessionStatsController.getD3StatsByProgramAndSD('0018t000002vfSfAAI','All','All','BLANK','500','All','All'));


String clientId,
    String programStr,
    String sdStr,
    String statusStr,
    String periodStr,
    String stageStr,
    String therapistStr
)


clientId: this.recordId,
          programStr: "All",
          sdStr: "All",
          periodStr: "30",
          stageStr: "All",
          statusStr: "All",
          therapistStr: "All"